# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
# import os
# import sys
# sys.path.insert(0, os.path.abspath('.'))


# -- Project information -----------------------------------------------------

project = "鸽园"
copyright = "2021-2022, JamzumSum"
author = "JamzumSum"

# The full version, including alpha/beta/rc tags
release = "0.1.0"


# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = ["myst_parser", "sphinx.ext.mathjax", "sphinx.ext.githubpages"]

# Add any paths that contain templates here, relative to this directory.
templates_path = ["_templates"]

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = "zh_CN"

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = ["_snippets"]


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = "press"

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ["_static"]

# customized sidebar
html_sidebars = {"**": ["util/searchbox.html", "util/sidebar.html"]}

# additional pages
html_additional_pages = {"donate": "merger.html"}

html_baseurl = "www.zzsblog.top"
html_search_language = "zh"
html_favicon = "_static/favicon.png"
html_logo = html_favicon

# press-theme configs
html_theme_options = {
    "external_links": [
        ("首页", "index.html"),
        ("关于", "about.html"),
        ("捐赠", "donate.html"),
        ("GitHub", "https://github.com/JamzumSum/zzsblog.github.io"),
    ]
}

# myst configs
myst_enable_extensions = ["dollarmath", "substitution"]
myst_substitutions = {"cname": html_baseurl}
myst_heading_anchors = 3
